name: caller_workflow
on: 
 workflow_dispatch:
jobs:
 calling-test-job:
  uses: Suraj-kaul/fresher-trainee---Ec2_instance/.github/workflows/deploy.yml@master
  permissions:
      id-token: write
      contents: read

  secrets: inherit
  with:
      aws_role_arn: arn:aws:iam::528519205020:role/pinkesh-TU

