name: caller_workflow
on:
 workflow_dispatch:
jobs:
 calling-test-job:
  uses: Suraj-kaul/fresher-trainee---Ec2_instance/.github/workflows/deploy.yml@master
  # with:
  #  role: arn:aws:iam::528519205020:role/pinkesh-TU
  permissions:
   id-token: write
   contents: read
  

  # # secrets: inherit
  # with:
  #     role: arn:aws:iam::528519205020:role/pinkesh-TU

